spring.application.name=patient-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/mic_session06db?currentSchema=patientdb
spring.datasource.username=postgres
spring.datasource.password=000000
spring.jpa.hibernate.ddl-auto=update

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
