spring.application.name=appointment-service

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/mic_session06db?currentSchema=appointmentdb
spring.datasource.username=postgres
spring.datasource.password=000000
spring.jpa.hibernate.ddl-auto=update

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

server.error.include-message=always

resilience4j.circuitbreaker.instances.doctorServiceCB.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.doctorServiceCB.ignore-exceptions=ra.appointmentservice.exception.InvalidAppointmentReferenceException

resilience4j.circuitbreaker.instances.doctorServiceCB.minimum-number-of-calls=5

resilience4j.circuitbreaker.instances.doctorServiceCB.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.doctorServiceCB.permitted-number-of-calls-in-half-open-state=3

# Retry
resilience4j.retry.instances.patientRetry.max-attempts=3

resilience4j.retry.instances.patientRetry.wait-duration=2s

resilience4j.retry.instances.patientRetry.retry-exceptions=org.springframework.web.client.ResourceAccessException

# 404
resilience4j.retry.instances.patientRetry.ignore-exceptions=ra.appointmentservice.exception.InvalidAppointmentReferenceException

logging.level.io.github.resilience4j=DEBUG
logging.level.io.github.resilience4j.circuitbreaker=DEBUG
logging.level.io.github.resilience4j.retry=DEBUG

logging.level.ra.appointmentservice=INFO