spring.application.name=medical-discovery-server

server.port=8761

# Server không t? ??ng ký chính mình
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# T?t self-preservation ?? Server c?p nh?t tr?ng thái các service nhanh h?n
eureka.server.enable-self-preservation=false